version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    environment:
      - N8N_EDITOR_BASE_URL=http://127.0.0.1:5678/
      - WEBHOOK_URL=http://127.0.0.1:5678/

volumes:
  n8n_data:
    external: true
